name: ecommerce_analytics
version: '1.0'
config-version: 2

profile: ecommerce_profile

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  ecommerce_analytics:
    +materialized: view
